const getRandomNameCar = (): string => {
    const carBrands: { [key: string]: string[] } = {
        Toyota: [
            'Camry',
            'Corolla',
            'Rav4',
            'Prius',
            'Highlander',
            'Tacoma',
            'Sienna',
            '4Runner',
            'Tundra',
            'C-HR',
        ],
        Honda: [
            'Accord',
            'Civic',
            'CR-V',
            'Pilot',
            'Odyssey',
            'HR-V',
            'Fit',
            'Insight',
            'Ridgeline',
            'Passport',
        ],
        Ford: [
            'F-150',
            'Escape',
            'Explorer',
            'Focus',
            'Mustang',
            'Edge',
            'Fusion',
            'Ranger',
            'Expedition',
            'Bronco',
        ],
        Chevrolet: [
            'Silverado',
            'Equinox',
            'Traverse',
            'Malibu',
            'Tahoe',
            'Suburban',
            'Camaro',
            'Colorado',
            'Blazer',
            'Trax',
        ],
        Volkswagen: [
            'Jetta',
            'Tiguan',
            'Passat',
            'Atlas',
            'Golf',
            'Arteon',
            'ID.4',
            'Taos',
            'Touareg',
            'Atlas Cross Sport',
        ],
        Nissan: [
            'Altima',
            'Rogue',
            'Sentra',
            'Murano',
            'Versa',
            'Pathfinder',
            'Maxima',
            'Titan',
            'Kicks',
            'Frontier',
        ],
        BMW: [
            '3 Series',
            '5 Series',
            'X3',
            'X5',
            '7 Series',
            'X1',
            '4 Series',
            'X7',
            'X6',
            '2 Series',
        ],
        'Mercedes-Benz': [
            'C-Class',
            'E-Class',
            'GLC',
            'GLE',
            'A-Class',
            'S-Class',
            'CLA',
            'GLB',
            'GLA',
            'GLS',
        ],
        Audi: ['A4', 'Q5', 'Q7', 'A3', 'Q3', 'A6', 'A5', 'A7', 'Q8', 'e-tron'],
        Tesla: [
            'Model 3',
            'Model Y',
            'Model S',
            'Model X',
            'Cybertruck',
            'Roadster',
        ],
    };

    const brands = Object.keys(carBrands);
    const randomBrand = brands[Math.floor(Math.random() * brands.length)];
    const models = carBrands[randomBrand];
    const randomModel = models[Math.floor(Math.random() * models.length)];
    return `${randomBrand} ${randomModel}`;
};

export default getRandomNameCar;
